[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crispy-bootstrap5>=2024.10",
    "django>=5.1.7",
    "django-crispy-forms>=2.3",
    "pillow>=11.1.0",
    "whitenoise>=6.9.0",
]
